title: # Name of API
description: # Brief description about the API
base_url: # Base of all enpoint URls.

endpoints:
  endpoint_1:
    path: # Path after base URL
    method: # HTTP Request Method
    request_headers: # Dictionary of headers
    payload: # An object
      data_type: # Pythonic data types: list|dict|int|str|bool|None
      fuzz_prob: # Floating point value in range [0,1] defining how often to modify value
      payload: # In case of nested data structures like list and dict
      seeds: # List of seed inputs in case of mutation fuzzer
      grammar: # Grammar in case of grammar fuzzer
        min_nonterminals:
        max_nonterminals:
        expansions:
        start:
    responses:
      status: # An integer
        data: # Data expected with current status code
          data_type: # Pythonic data types: list|dict|int|str|bool|None
          exact: # Boolean value to define if payload must match exactly as configured
          payload: # In case of nested data structures like list and dict
        headers: # Dictionary of headers
