title: Floo Backend
description: Shreyas the One
base_url: http://localhost:54321/api/

endpoints:
  endpoint1_name:
    path: meeting/new/
    method: GET
    request_headers:
      Content-Length: '100'
      Content-Type: application/json
      Content-Encoding: utf-8
      Content-Language: english
      Content-Location: Roorkee
    payload:
      data_type: dict
      exact: False
      payload: 
        team:
          data_type: str
          exact: False
          payload: null
    responses:
      201:
        data: 
          data_type: dict
          exact: True
          payload:
            code:
              data_type: str
              exact: False
              payload: code
        headers:

  endpoint2_name:
    path: team/join/
    method: GET
    request_headers:
      Content-Length: '100'
      Content-Type: application/json
      Content-Encoding: utf-8
      Content-Language: english
      Content-Location: Roorkee
    payload:
      data_type: int
      exact: True
      payload: 0

    responses:
      400:
        data: 
          data_type: dict
          exact: True
          payload:
            code:
              data_type: str
              exact: False
              payload: "Team does not exist"
        headers: